import pathlib
content = pathlib.Path('src/testgen/cli.py').read_text(encoding='utf-8')

# Fix the malformed header string block
old = '''            header = (
                f""""""Auto-generated by testgen.
model={model} prompt_version={CODE_MODE_VERSION} temperature={temperature}
run_id={run_id}
REVIEW BEFORE COMMITTING. Generated tests may encode existing defects.
"""
"""
            )'''

new = '''            header = (
                'Auto-generated by testgen. '
                f'model={model} prompt={CODE_MODE_VERSION} temp={temperature} '
                f'run_id={run_id}\\n'
                'REVIEW BEFORE COMMITTING. Tests may encode existing defects.\\n'
            )'''

content = content.replace(old, new)
pathlib.Path('src/testgen/cli.py').write_text(content, encoding='utf-8')
print('cli.py patched')
