Auto-generated by testgen. model=gpt-4o-mini prompt=CODE_MODE_V3 temp=0.2 run_id=run_09e4d923
REVIEW BEFORE COMMITTING. Tests may encode existing defects.
import pytest
from module_under_test import *


@pytest.mark.parametrize("a,b,expected", [(2, 3, 5), (0, 0, 0), (-1, 1, 0)])
def test_add_happy_path(a, b, expected):
    assert add(a, b) == expected


def test_add_negative_raises():
    with pytest.raises(ValueError):
        add(-1, 2)