"""Typer CLI: generate | testplan | bench | report | gate"""
from __future__ import annotations
import csv, json, sys, time, uuid
from pathlib import Path
from typing import Optional
import typer
from rich.console import Console
from testgen.config import cfg
from testgen.clients import get_client
from testgen.extractor import extract_functions
from testgen.prompts import (
    build_code_mode_prompt, build_spec_mode_prompt, build_test_plan_prompt,
    CODE_MODE_VERSION, SPEC_MODE_VERSION, TEST_PLAN_VERSION,
)
from testgen.repair import generate_with_repair
from testgen.models import RunReport, TestPlan, TestPlanRow, BenchmarkEntry
from testgen.reporter import print_run_summary, write_json_report, write_markdown_report, generate_benchmark_charts
from testgen.store import Store

app = typer.Typer(name="testgen", help="AI-powered pytest generation.", add_completion=False)
console = Console()
err = Console(stderr=True)


def _make_store() -> Store:
    return Store(cfg.db_path)


@app.command()
def generate(
    input: str = typer.Option(..., help=".py file to generate tests for (code mode)."),
    function: Optional[str] = typer.Option(None, help="Only generate for this function."),
    backend: str = typer.Option(cfg.backend, help="LLM backend: openai | openrouter | vllm | fake"),
    model: str = typer.Option(cfg.model),
    temperature: float = typer.Option(cfg.temperature),
    target_coverage: float = typer.Option(cfg.target_coverage),
    max_iters: int = typer.Option(cfg.max_iterations),
    out: Optional[str] = typer.Option(None),
    run_mutation: bool = typer.Option(False, help="Run mutation testing on final output."),
    no_store: bool = typer.Option(False),
):
    """Generate a pytest suite from a .py file."""
    cfg.ensure_dirs()
    if backend == "openrouter" and model == "gpt-4o-mini":
        model = "deepseek/deepseek-v4-flash-0731:free"
    client = get_client(backend, model, cache_dir=cfg.cache_dir)
    store = _make_store() if not no_store else None
    specs = extract_functions(input, function)
    if not specs:
        err.print(f"[red]No matching functions found in {input}[/red]")
        raise typer.Exit(4)
    module_source = Path(input).read_text(encoding="utf-8")
    exit_code = 0
    for spec_obj in specs:
        run_id = f"run_{uuid.uuid4().hex[:8]}"
        out_dir = Path(cfg.results_dir) / run_id
        messages = build_code_mode_prompt(spec_obj)
        console.rule(f"[bold cyan]{spec_obj.qualname}[/bold cyan] -- code mode")
        final_code, final_result, attempts = generate_with_repair(
            client=client, initial_messages=messages, module_source=module_source,
            function_name=spec_obj.name, mode="code", model=model,
            prompt_version=CODE_MODE_VERSION, temperature=temperature,
            target_coverage=target_coverage, max_iters=max_iters,
            log_path=out_dir / "attempts.json",
        )
        if final_result is None:
            final_status = "error"; exit_code = max(exit_code, 1)
        elif final_result.failed > 0 or final_result.errors > 0:
            final_status = "failed"; exit_code = max(exit_code, 3)
        elif final_result.branch_coverage < target_coverage:
            final_status = "coverage_not_met"; exit_code = max(exit_code, 3)
        else:
            final_status = "passed"
        mutation_score = None
        if run_mutation and final_code and final_result:
            from testgen.mutator import score_mutation
            mut_report = score_mutation(module_source, final_code, max_mutants=cfg.max_mutants)
            mutation_score = mut_report.mutation_score
        report = RunReport(
            run_id=run_id, function=spec_obj.name, module_path=spec_obj.module_path,
            mode="code", model=model, prompt_version=CODE_MODE_VERSION,
            temperature=temperature, target_coverage=target_coverage,
            attempts=attempts, final_code=final_code, final_status=final_status,
            branch_coverage=final_result.branch_coverage if final_result else 0.0,
            mutation_score=mutation_score,
        )
        print_run_summary(report)
        if final_code:
            out_path = Path(out) if out else Path(f"tests/test_{spec_obj.name}.py")
            out_path.parent.mkdir(parents=True, exist_ok=True)
            header = (
                '# Auto-generated by testgen. '
                f'model={model} prompt={CODE_MODE_VERSION} temp={temperature} '
                f'run_id={run_id}\n'
                '# REVIEW BEFORE COMMITTING. Tests may encode existing defects.\n\n'
            )
            out_path.write_text(header + final_code, encoding="utf-8")
            console.print(f"[green]Written:[/green] {out_path}")
        write_json_report(report, out_dir)
        write_markdown_report(report, out_dir)
        if store:
            store.save_run(report)
    raise typer.Exit(exit_code)


@app.command()
def testplan(
    spec: Optional[str] = typer.Option(None, help="Requirement text inline"),
    spec_file: Optional[str] = typer.Option(None, help="Path to .txt requirement file"),
    backend: str = typer.Option(cfg.backend),
    model: str = typer.Option(cfg.model),
    format: str = typer.Option("markdown", help="markdown | csv"),
    out: Optional[str] = typer.Option(None),
):
    """Generate a structured test plan from a requirement description."""
    if not spec and not spec_file:
        err.print("[red]Provide --spec TEXT or --spec-file PATH[/red]"); raise typer.Exit(4)
    spec_text = spec if spec else Path(spec_file).read_text(encoding="utf-8")
    cfg.ensure_dirs()
    if backend == "openrouter" and model == "gpt-4o-mini":
        model = "deepseek/deepseek-v4-flash-0731:free"
    client = get_client(backend, model, cache_dir=cfg.cache_dir)
    resp = client.generate(build_test_plan_prompt(spec_text), temperature=0.2)
    raw_text = resp.text.strip()
    if "```" in raw_text:
        import re
        m = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", raw_text)
        if m:
            raw_text = m.group(1).strip()
    try:
        rows_raw = json.loads(raw_text)
    except json.JSONDecodeError:
        err.print(f"[red]Model did not return valid JSON[/red]"); raise typer.Exit(1)
    rows = [TestPlanRow(**r) for r in rows_raw]
    ext = "md" if format == "markdown" else "csv"
    out_path = Path(out) if out else Path(cfg.results_dir) / f"testplan.{ext}"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if format == "csv":
        with out_path.open("w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=["id","category","precondition","steps","expected_result","priority"])
            w.writeheader(); w.writerows(r.model_dump() for r in rows)
    else:
        lines = ["| ID | Category | Precondition | Steps | Expected | Priority |", "|---|---|---|---|---|---|"]
        for r in rows:
            lines.append(f"| {r.id} | {r.category} | {r.precondition} | {r.steps} | {r.expected_result} | {r.priority} |")
        out_path.write_text(chr(10).join(lines), encoding="utf-8")
    console.print(f"[green]Test plan written:[/green] {out_path} ({len(rows)} cases)")


@app.command()
def report(limit: int = typer.Option(10)):
    """Show recent runs from the SQLite store."""
    from rich.table import Table; from rich import box
    store = _make_store()
    runs = store.list_runs(limit=limit)
    if not runs:
        console.print("[yellow]No runs found. Run testgen generate first.[/yellow]"); raise typer.Exit(0)
    tbl = Table(title="Recent Runs", box=box.ROUNDED, header_style="bold cyan")
    for col in ["ID", "Function", "Mode", "Model", "Status", "Coverage%", "Mutation%", "Created"]:
        tbl.add_column(col)
    for r in runs:
        tbl.add_row(r["id"], r["function"], r["mode"], r["model"], r["final_status"],
                    str(r["coverage_pct"]) + "%" if r["coverage_pct"] else "?",
                    str(r["mutation_pct"]) + "%" if r["mutation_pct"] else "?", r["created_at"])
    console.print(tbl)


@app.command()
def gate(
    min_mutation_score: float = typer.Option(0.60),
    min_coverage: float = typer.Option(0.75),
):
    """CI quality gate: exits 1 if benchmark metrics drop below thresholds."""
    from testgen.gate import run_gate
    raise typer.Exit(run_gate(cfg.db_path, min_mutation_score, min_coverage))


def main():
    app()


if __name__ == "__main__":
    main()
